# Generated by Django 6.1 on 2026-08-31 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_userskill'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userskill',
            name='unique_user_skill',
        ),
        migrations.DeleteModel(
            name='UserSkill',
        ),
    ]
