# Generated by Django 6.1 on 2026-09-08 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0004_remove_userskill_unique_user_skill_delete_userskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('opportunity_type', models.CharField(choices=[('job', 'Job'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('scholarship', 'Scholarship')], default='job', max_length=20)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('is_remote', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-created_at'],
            },
        ),
    ]
