# Generated by Django 6.1 on 2026-08-31 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-created_at'], 'verbose_name': 'Learning Resource', 'verbose_name_plural': 'Learning Resources'},
        ),
    ]
